#!/bin/sh
#
# $Id$
#

if test -z "$1"; then
    echo "Usage: $0 directory ..." 1>&2
    exit 1
fi

total=0
while test -n "$1"; do
    files=`/usr/bin/find "$1" -type f | /usr/bin/wc -l`
    total=$(($total+$files))
    shift
done

if test $total -gt 0; then
    echo "Target is not empty"
    exit 2
fi
echo "Target is empty"
exit 0
