#!/bin/bash
#
# $Id$
#

shopt -s extglob

export PATH=/bin:/usr/bin

if test -z "$1"; then
	echo "Usage: $0 path_to_instance"
	exit 1
fi

instance="$1"

count=0
for source in `sed -n '/<filestorage/,/<\/filestorage>/ {
                    /^ *path/ {
			s#^ *path *\$INSTANCE/\(.*\)$#\1#g; p
                    }
                }' ${instance}/etc/@(zope|zeo).conf`; do
	count=$((count++))
	# Determine free space on mount point
	freeblocks=`stat --filesystem --format="%f" "$instance/$source"`
	blocksize=`stat --filesystem --format="%s" "$instance/$source"`
	free=$((freeblocks*blocksize))

	# Get size of Data.fs
	size=`stat --format="%s" "$instance/$source"`

	# Check that size Data.fs is smaller than free space
	if test $free -lt $size; then
		echo "$source needs packing: $size > $free"
		exit 2
	fi
done

if test $count -lt 1; then
	echo "No Data.fs files found"
	exit 2
fi

echo "Data.fs files don't need packing (yet)"
exit 0
